/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {};

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AddStock: typeof import('./src/components/addStock.vue')['default']
    AuthForm: typeof import('./src/components/AuthForm.vue')['default']
    BottomNav: typeof import('./src/components/bottomNav.vue')['default']
    CreateNewIngredient: typeof import('./src/components/CreateNewIngredient.vue')['default']
    DeleteStockItemDialog: typeof import('./src/components/DeleteStockItemDialog.vue')['default']
    DialogBase: typeof import('./src/components/common/DialogBase.vue')['default']
    EditIngredient: typeof import('./src/components/EditIngredient.vue')['default']
    EditStockItemDialog: typeof import('./src/components/EditStockItemDialog.vue')['default']
    ErrorAlert: typeof import('./src/components/common/ErrorAlert.vue')['default']
    FormLayout: typeof import('./src/components/common/FormLayout.vue')['default']
    FormTextField: typeof import('./src/components/common/FormTextField.vue')['default']
    IngredientForm: typeof import('./src/components/common/IngredientForm.vue')['default']
    InteractWithIngredient: typeof import('./src/components/InteractWithIngredient.vue')['default']
    ItemList: typeof import('./src/components/common/ItemList.vue')['default']
    ListIngredients: typeof import('./src/components/listIngredients.vue')['default']
    LoadingIndicator: typeof import('./src/components/common/LoadingIndicator.vue')['default']
    NutritionForm: typeof import('./src/components/common/NutritionForm.vue')['default']
    QuantityInput: typeof import('./src/components/common/QuantityInput.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UnitSelect: typeof import('./src/components/common/UnitSelect.vue')['default']
  }
}
