/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {};

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AddStock: typeof import('./src/components/Stock/AddStock.vue')['default']
    AddStockItemDialog: typeof import('./src/components/Stock/AddStockItemDialog.vue')['default']
    AuthForm: typeof import('./src/components/Auth/AuthForm.vue')['default']
    BaseList: typeof import('./src/components/Base/BaseList.vue')['default']
    BottomNav: typeof import('./src/components/Base/BottomNav.vue')['default']
    CreateNewIngredient: typeof import('./src/components/Ingredients/CreateNewIngredient.vue')['default']
    DeleteStockItemDialog: typeof import('./src/components/Stock/DeleteStockItemDialog.vue')['default']
    DialogBase: typeof import('./src/components/common/DialogBase.vue')['default']
    EditIngredient: typeof import('./src/components/forms/EditIngredient.vue')['default']
    EditStockItemDialog: typeof import('./src/components/Stock/EditStockItemDialog.vue')['default']
    ErrorAlert: typeof import('./src/components/common/ErrorAlert.vue')['default']
    FormLayout: typeof import('./src/components/forms/FormLayout.vue')['default']
    FormTextField: typeof import('./src/components/forms/FormTextField.vue')['default']
    IngredientCreate: typeof import('./src/components/Ingredient/IngredientCreate.vue')['default']
    IngredientDropDown: typeof import('./src/components/Ingredient/IngredientDropDown.vue')['default']
    IngredientForm: typeof import('./src/components/Ingredients/IngredientForm.vue')['default']
    IngredientList: typeof import('./src/components/Ingredient/IngredientList.vue')['default']
    InteractWithIngredient: typeof import('./src/components/Ingredients/InteractWithIngredient.vue')['default']
    ItemList: typeof import('./src/components/common/ItemList.vue')['default']
    ListIngredients: typeof import('./src/components/Ingredients/ListIngredients.vue')['default']
    LoadingIndicator: typeof import('./src/components/common/LoadingIndicator.vue')['default']
    LoginFrom: typeof import('./src/components/Auth/LoginFrom.vue')['default']
    NutritionForm: typeof import('./src/components/common/NutritionForm.vue')['default']
    QuantityInput: typeof import('./src/components/common/QuantityInput.vue')['default']
    RecepieCreateForm: typeof import('./src/components/Recepie/RecepieCreateForm.vue')['default']
    RecepieList: typeof import('./src/components/Recepie/RecepieList.vue')['default']
    RegisterForm: typeof import('./src/components/Auth/RegisterForm.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SelectIngredientRow: typeof import('./src/components/Ingredients/SelectIngredientRow.vue')['default']
    StockCreate: typeof import('./src/components/Stock/StockCreate.vue')['default']
    StockDelet: typeof import('./src/components/Stock/StockDelet.vue')['default']
    StockList: typeof import('./src/components/Stock/StockList.vue')['default']
    UnitDropDown: typeof import('./src/components/Base/UnitDropDown.vue')['default']
    UnitSelect: typeof import('./src/components/common/UnitSelect.vue')['default']
  }
}
