/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AddStock: typeof import('./src/components/forms/AddStock.vue')['default']
    AddStockItemDialog: typeof import('./src/components/dialoges/AddStockItemDialog.vue')['default']
    AuthForm: typeof import('./src/components/forms/AuthForm.vue')['default']
    BottomNav: typeof import('./src/components/BottomNav.vue')['default']
    CreateNewIngredient: typeof import('./src/components/forms/CreateNewIngredient.vue')['default']
    DeleteStockItemDialog: typeof import('./src/components/dialoges/DeleteStockItemDialog.vue')['default']
    DialogBase: typeof import('./src/components/dialoges/DialogBase.vue')['default']
    EditIngredient: typeof import('./src/components/forms/EditIngredient.vue')['default']
    EditStockItemDialog: typeof import('./src/components/dialoges/EditStockItemDialog.vue')['default']
    ErrorAlert: typeof import('./src/components/common/ErrorAlert.vue')['default']
    FormLayout: typeof import('./src/components/forms/FormLayout.vue')['default']
    FormTextField: typeof import('./src/components/forms/FormTextField.vue')['default']
    IngredientForm: typeof import('./src/components/forms/IngredientForm.vue')['default']
    InteractWithIngredient: typeof import('./src/components/forms/InteractWithIngredient.vue')['default']
    ItemList: typeof import('./src/components/common/ItemList.vue')['default']
    ListIngredients: typeof import('./src/components/ListIngredients.vue')['default']
    LoadingIndicator: typeof import('./src/components/common/LoadingIndicator.vue')['default']
    NutritionForm: typeof import('./src/components/common/NutritionForm.vue')['default']
    QuantityInput: typeof import('./src/components/common/QuantityInput.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SelectIngredientRow: typeof import('./src/components/forms/SelectIngredientRow.vue')['default']
    UnitSelect: typeof import('./src/components/common/UnitSelect.vue')['default']
  }
}
