erDiagram
    User ||--o{ Stock: has
    User ||--o{ Recipe: creates
    User ||--o{ ShoppingList: creates
    ShoppingList ||--o{ FullIngredient: contains
    Stock ||--o{ FullIngredient: contains
    Recipe ||--o{ RecipeIngredient: contains
    RecipeIngredient ||--o{ FullIngredient: are
